---
- name: Configure AWS server
  hosts: all
  become: true
  vars:
    new_username: "deployer"
    sudoers_file: "/etc/sudoers.d/90-{{ new_username }}"

  tasks:
    - name: Create new user
      user:
        name: "{{ new_username }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        create_home: yes
        home: "/home/{{ new_username }}"
        password_lock: yes

    - name: Create .ssh directory
      file:
        path: "/home/{{ new_username }}/.ssh"
        state: directory
        mode: 0700
        owner: "{{ new_username }}"
        group: "{{ new_username }}"

    - name: Add current SSH key to authorized_keys
      authorized_key:
        user: "{{ new_username }}"
        state: present
        key: "{{ lookup('file', '/home/ubuntu/.ssh/authorized_keys') }}"

    - name: Configure sudo access
      copy:
        content: "{{ new_username }} ALL=(ALL) NOPASSWD:ALL\n"
        dest: "{{ sudoers_file }}"
        mode: 0440
        validate: 'visudo -cf %s'

    - name: Harden SSH configuration
      blockinfile:
        path: /etc/ssh/sshd_config
        block: |
          PasswordAuthentication no
          AllowUsers {{ new_username }} ubuntu
      notify: restart sshd

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
