- name: Generate SSH key on Jenkins server and propagate to target server
  hosts: localhost
  gather_facts: false
  vars:
    ssh_key_path: /home/ubuntu/.ssh/id_rsa
    public_key_path: /home/ubuntu/.ssh/id_rsa.pub
    remote_user: jenkins_deploy
  tasks:
    - name: Generate SSH key pair if not exists
      become: true
      become_user: ubuntu
      openssh_keypair:
        path: "{{ ssh_key_path }}"
        type: rsa
        size: 2048
        mode: '0600'
      register: ssh_key_result

    - name: Read the public key
      become: true
      become_user: ubuntu
      slurp:
        src: "{{ public_key_path }}"
      register: pubkey_raw

    - name: Set fact for Jenkins public key
      set_fact:
        jenkins_pub_key: "{{ pubkey_raw.content | b64decode }}"

- name: Create remote user and install Jenkins key
  hosts: all
  become: true
  vars:
    remote_user: jenkins_deploy
  tasks:
    - name: Create a new user with sudo privileges
      user:
        name: "{{ remote_user }}"
        shell: /bin/bash
        groups: sudo
        state: present
        create_home: true

    - name: Create .ssh directory for new user
      file:
        path: "/home/{{ remote_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"

    - name: Add Jenkins public key to authorized_keys
      copy:
        content: "{{ hostvars['localhost']['jenkins_pub_key'] }}"
        dest: "/home/{{ remote_user }}/.ssh/authorized_keys"
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
        mode: '0600'

    - name: Allow passwordless sudo for new user
      lineinfile:
        path: "/etc/sudoers.d/{{ remote_user }}"
        create: yes
        mode: '0440'
        line: "{{ remote_user }} ALL=(ALL) NOPASSWD:ALL"
