---
- name: Generate SSH key on Jenkins server and propagate to target server
  hosts: localhost
  gather_facts: false

  vars:
    ssh_key_path: /var/lib/jenkins/.ssh/id_rsa
    public_key_path: /var/lib/jenkins/.ssh/id_rsa.pub
    target_user: jenkins 

  tasks:

    - name: Generate SSH key pair if not exists
      community.crypto.openssh_keypair:
        path: "{{ ssh_key_path }}"
        type: rsa
        size: 2048
        force: false

    - name: Read the public key
      slurp:
        src: "{{ public_key_path }}"
      register: pub_key_content

- name: Create user and copy public key on remote hosts
  hosts: target
  become: true
  gather_facts: false

  vars:
    target_user: rpx

  tasks:
    - name: Ensure user exists
      ansible.builtin.user:
        name: "{{ target_user }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        create_home: yes

    - name: Add public key to authorized_keys
      ansible.posix.authorized_key:
        user: "{{ target_user }}"
        state: present
        key: "{{ hostvars['localhost'].pub_key_content.content | b64decode }}"
